# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_auth', '0005_auto_20160727_2333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersocialauth',
            unique_together=set([('provider', 'uid', 'user')]),
        ),
    ]
